sudo: false
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
install:
  - pip install tox-travis
script:
  - tox
  - coverage run --source icon_font_to_png -m py.test
  - coverage report -m
after_success:
  - coveralls
